<html>
<head>
<?php
echo '<title>My First PHP Script</title>';
?>
</head>
<body>
<?php
       echo '<p>Hello Developer ! Welcome to your PHP Script !!</p>';
?>
<p>This content is generated by your basic PHP Script!!!</p>
</body>
</html>